apiVersion: v1
kind: Service
metadata:
  name: dotnetcoretest
  namespace: {{ .Release.Namespace }}
  labels:
    app: dotnetcoretest
spec:
  type: LoadBalancer
  selector:
    app: dotnetcoretest
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
