---
spec_version: '1.0'
indicators:
  response_time_p50: histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{controller="WeatherForecast",job="$SERVICE-$PROJECT-$STAGE-canary"}[$DURATION_SECONDS])))
  response_time_p90: histogram_quantile(0.9, sum by(le) (rate(http_request_duration_seconds_bucket{controller="WeatherForecast",job="$SERVICE-$PROJECT-$STAGE-canary"}[$DURATION_SECONDS])))
  response_time_p95: histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{controller="WeatherForecast",job="$SERVICE-$PROJECT-$STAGE-canary"}[$DURATION_SECONDS])))
